### PR TITLE
Fix for Snap to Surface

### PR DESCRIPTION
**Pull request by AlphaAsh**
By Ravencrow

### CODE REVIEW

**Comment by medsouz** [comment]
Looks good, you just gotta tell Ravencrow to switch her IDE from spaces to tabs. :smile:

**Comment by ghost** [comment]
I smiled...

``` c#
- Debug.Log("KK: Deselecting an object");
+ Debug.Log("KK: Deselecting an object.");
```

**Comment by AlphaAsh** [comment]
Never let this OCD loon near your code. For medsouz, it is.... dum dum dum.... too late.

**Comment by medsouz** [comment]
Nononono this is important! My compiler is very sensitive to improper punctuation in output.

**Pull request merged**
